In [1]:
import numpy as np

- 1차원 벡터 생성

In [3]:
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

In [4]:
print(type(array1))

<class 'numpy.ndarray'>


In [5]:
array1.shape

(3,)

- 2차원 행열 생성

In [7]:
array2 = np.array([[1,2,3],[4,5,6]])
print(array2)
print(type(array2))
print(array2.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [8]:
array3 = np.array([[1,2,3]])
print(array3)
print(array3.shape)

[[1 2 3]]
(1, 3)


In [10]:
print("array1 : {}차원, array2: {}차원, array3: {}차원".format(array1.ndim, array2.ndim, array3.ndim))

array1 : 1차원, array2: 2차원, array3: 2차원


In [11]:
list1 = [7,8,9]

In [13]:
array1 = np.array(list1)

In [15]:
print(type(list1), array1, type(array1), array1.dtype)

<class 'list'> [7 8 9] <class 'numpy.ndarray'> int32


In [16]:
array2 = np.array([1,2,7.5])
print(array2, array2.dtype)

[1.  2.  7.5] float64


In [17]:
array3 = np.array([45,55,'test'])
print(array3, array3.dtype)

['45' '55' 'test'] <U11


- astype() : 타입 변환

In [18]:
array1 = np.array([1,2,3])
print(array1.dtype)

int32


In [19]:
array1_float = array1.astype('float64')
print(array1_float.dtype)

float64


In [20]:
array1_int = array1_float.astype('int32')
print(array1_int.dtype)

int32


In [21]:
array2 = np.array([1.2,2.2,3.2])
array2_int = array2.astype('int32')
print(array2.dtype, array2_int.dtype)

float64 int32


- ndarray 를 손쉽게 생성 : arange, zeros, ones

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
np.arange(15,21)

array([15, 16, 17, 18, 19, 20])

In [28]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [29]:
np.arange(5,101,5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [3]:
np.zeros(4)

array([0., 0., 0., 0.])

In [4]:
np.zeros(4, dtype='int32')

array([0, 0, 0, 0])

In [5]:
np.ones((2,2),dtype='int32')

array([[1, 1],
       [1, 1]])

In [6]:
np.ones((2,3,2),dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

- empty(), full()

In [7]:
np.empty(4)   #초기화되지 않은 형태로 생성(임의의 값이 들어옴)

array([0., 0., 0., 0.])

In [8]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

- eye() : 단위행렬 생성

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

- linspace() : 일정한 간격의 ndarray 생성할 때 사용

In [39]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [40]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [41]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

- 차원 변경 : reshape()

In [3]:
array1 = np.arange(10) 
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# array1 2차원 변경

array2 = array1.reshape(2,5)
array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
array3 = array1.reshape(5,2)
array3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [4]:
array1.reshape(4,3) # 만들 수 없는 형태를 시도하면 에러 발생

ValueError: cannot reshape array of size 10 into shape (4,3)

In [46]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
array1.reshape(-1,5)  # 원하는 행, 열 구조만 입력한 후 나머지는 알아서 처리

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
array1.reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

- np.random.rand(숫자) : 0~1 사이의 숫자가 랜덤으로 생성

In [13]:
np.random.rand(2,3)

array([[0.55869592, 0.00470909, 0.27384705],
       [0.91974546, 0.38624297, 0.06351283]])

- np.random.randn(숫자) : 정규분포로 샘플링 된 랜덤으로 생성

In [14]:
np.random.randn(5)

array([-0.17712636,  0.36949882, -1.83659407,  0.67341962,  1.25046598])

In [15]:
np.random.randn(3,4,2)

array([[[-0.34268286,  0.63513527],
        [ 0.77267567, -2.07505237],
        [ 0.01436217,  0.11813348],
        [ 0.7900234 , -0.18771488]],

       [[ 1.076024  ,  0.65084021],
        [-0.31925771, -2.21890612],
        [-0.39185695,  1.04111391],
        [-0.21339553, -0.63078712]],

       [[ 1.61719372,  0.64899018],
        [ 1.45915419, -1.53162343],
        [-2.02304663, -0.98313067],
        [ 1.58410908, -0.37704222]]])

In [16]:
np.random.randn(5,1)

array([[-0.03751149],
       [ 0.16135754],
       [-0.83428404],
       [ 1.21751252],
       [-0.8287877 ]])

- np.random.randint(시작값, 마지막값, 사이즈) : 특정 정수 사이에서 랜덤 샘플링

In [18]:
np.random.randint(1, 10, 5)

array([8, 6, 3, 4, 5])

In [19]:
# 1 ~ 100 사이의 3, 5 행렬 생성
np.random.randint(1, 100, (3, 5))

array([[69, 57, 24, 14, 35],
       [99, 42, 93, 21, 82],
       [97, 69, 93, 48, 78]])

- seed(임의의 숫자) : 랜덤한 값을 동일하게 다시 생성할 때 사용

In [24]:
np.random.seed(100)
np.random.randn(3, 4)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349]])

- choice
 - 주어진 ndarray로부터 랜덤으로 샘플링
 - 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [26]:
np.random.choice(100, size=(3, 4)) # np.arange(100) : 0 ~ 99 까지 범위

array([[83,  4, 91, 59],
       [67,  7, 49, 47],
       [65, 61, 14, 55]])

In [27]:
x = np.array([1, 2, 3, 1.5, 2.6, 3.9, 4.8])
np.random.choice(x, size = (2, 2))

array([[1.5, 1. ],
       [3. , 2. ]])

In [28]:
np.random.choice(x, size=(2, 2), replace=False)

array([[1. , 2.6],
       [4.8, 3.9]])

- 확률 분포에 따라 생성
 - uniform
 - normal

In [30]:
np.random.uniform(1.0, 3.0, size=(4, 5))

array([[2.20760908, 1.21029537, 1.76388689, 1.07295211, 2.78082313],
       [2.96184171, 1.11988398, 2.78109189, 2.153803  , 2.48495938],
       [2.26036787, 2.16368438, 1.04087826, 1.42005316, 2.08936976],
       [2.53823034, 1.50139046, 1.57179138, 2.70479018, 2.95001299]])

In [31]:
np.random.normal()

-0.3060978316537771

### 인덱싱
- 특정한 데이터 추출 : 원하는 위치의 인덱스 값 지정

- 슬라이싱 : 연속된 인덱싱 상의 ndarray 추출

- 팬시 인덱싱 : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터를 반환 받음

- 불린 인덱싱 : 특정 조건에 해당여부에 따라 추출

In [6]:
# 1 ~ 9 까지 ndarray 생성
array1 = np.arange(1, 10)
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
array1[2]

3

In [8]:
array1[-1]

9

In [34]:
array1[-3]

7

In [35]:
array1[2] = 13
array1

array([ 1,  2, 13,  4,  5,  6,  7,  8,  9])

In [40]:
array2 = np.arange(1, 10)
array2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
array2.reshape(3, 3)
array2_2d = array2.reshape(3, 3)

In [47]:
array2_2d[1]

array([4, 5, 6])

In [48]:
print(array2_2d[0, 0])
print(array2_2d[0, 2])
print(array2_2d[1, 1])
print(array2_2d[2, 1])
print(array2_2d[0, 0])

1
3
5
8
1


In [50]:
x = np.arange(36).reshape(3, 4, 3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [51]:
x[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [52]:
x[0, 1]

array([3, 4, 5])

In [53]:
x[0, 1, -1]

5

In [54]:
x[1]

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [58]:
# 16 출력
x[1, 1, 1]

16

In [59]:
x[1, 1, -2]

16

In [60]:
array2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
array2[0:3]

array([1, 2, 3])

In [62]:
array2[4:]

array([5, 6, 7, 8, 9])

In [63]:
array2[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
array2_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
array2_2d[0:2, 0:1] # [행, 열]

array([[1],
       [4]])

In [67]:
array2_2d[1:3, 0:3] # [행, 열]

array([[4, 5, 6],
       [7, 8, 9]])

In [70]:
# 2, 3, 5, 6 추출
array2_2d[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [72]:
# 팬시 인덱싱

array2_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
array2_2d[[0,1], 0:1]

array([[1],
       [4]])

In [74]:
array2_2d[[0,1]]

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
array2_2d[[0,1], 2]

array([3, 6])

In [76]:
# 5보다 큰 값만 추출
array1[array1 > 5]

array([13,  6,  7,  8,  9])

In [77]:
list1 = [1, 2, 3, 4, 5, 6 ,7 ,8, 9]
for i in list1:
    if i > 5:
        print(i)

6
7
8
9


In [79]:
# 1 ~ 100 사이의 임의의 정수 10개 추출

x = np.random.randint(1, 100, size = 10)
x

array([11, 14, 82, 26, 67, 16, 12, 39, 23, 56])

In [80]:
# 짝수만 추출

x[x % 2 == 0]

array([14, 82, 26, 16, 12, 56])

In [81]:
# 30 이상의 숫자 추출
x[x > 30]

array([82, 67, 39, 56])

- 다중 조건 사용하기
 - 파이썬 논리 연산자 and, or, not 사용불가
 - &, |, ! 사용

In [82]:
x

array([11, 14, 82, 26, 67, 16, 12, 39, 23, 56])

In [83]:
# 짝수이고, 70보다 작은 요소 추출
x[(x%2 == 0) & (x < 70)]

array([14, 26, 16, 12, 56])

In [84]:
# 30보다 크고 70보다 작은 요소 추출
x[(x > 30) & (x < 70)]

array([67, 39, 56])

In [85]:
temp = np.array([23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
     26.7, 25.1, 25.0, 22.7, 21.9, 23.6,
     24.9, 25.9, 23.8, 24.7, 25.6, 26.9,
     28.6, 28.0, 25.1, 26.7, 28.1, 26.5,
     26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])
temp

array([23.9, 24.4, 24.1, 25.4, 27.6, 29.7, 26.7, 25.1, 25. , 22.7, 21.9,
       23.6, 24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 28.6, 28. , 25.1, 26.7,
       28.1, 26.5, 26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [86]:
len(temp)

31

In [91]:
# 평균 기온이 25도를 넘는 일수?
len(temp[temp > 25.0])

21

### 데이터 형태 바꾸기
 - reshape()
 - ravel, np.ravel : 다차원 배열을 1차원으로 변경

In [93]:
x = np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [94]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [95]:
np.ravel(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [96]:
y = np.arange(15).reshape(3, 5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [110]:
y.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

ravel과 flatten 차이
 - ravel : 원본 데이터와 연결해서 가지고 있음(원본의 변화를 초래)
 - flatten : 원본 데이터를 복사해서 가지고 있음(원본의 변화와는 무관)

In [97]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [98]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [99]:
temp = x.ravel()
temp

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [100]:
temp2 = y.flatten()
temp2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [101]:
temp[0] = 100
temp2[0] = 100

In [103]:
print(x)
print(temp)

[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]


In [104]:
print(y)
print(temp2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]


In [105]:
x.ravel(order='F') # 열기준으로 1차원 변경

array([100,   5,  10,   1,   6,  11,   2,   7,  12,   3,   8,  13,   4,
         9,  14])

In [107]:
# 3차원 array 생성(3행 5열, 2개) => 0 ~ 30
x = np.arange(30).reshape(2, 3, 5)
x
# 3차원 => 변경

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [108]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

### 기본함수

#### 사칙연산
- add(), subtract(), multiply(), divide()
- 두 array의 shape 같아야 함

In [113]:
x = np.array([[4, 4, 4], [8, 8, 8]])
y = np.array([[1, 1, 1], [2, 2, 2]])

In [114]:
print(x)
print(y)

[[4 4 4]
 [8 8 8]]
[[1 1 1]
 [2 2 2]]


In [115]:
x + y

array([[ 5,  5,  5],
       [10, 10, 10]])

In [116]:
np.add(x, y)

array([[ 5,  5,  5],
       [10, 10, 10]])

In [117]:
x * y

array([[ 4,  4,  4],
       [16, 16, 16]])

In [118]:
np.multiply(x, y)

array([[ 4,  4,  4],
       [16, 16, 16]])

In [119]:
x / y

array([[4., 4., 4.],
       [4., 4., 4.]])

In [120]:
np.divide(x, y)

array([[4., 4., 4.],
       [4., 4., 4.]])

#### 통계 함수 : 최대값, 최소값, 평균, 분산

In [122]:
x = np.random.rand(15).reshape(3, 5)
x

array([[0.183279  , 0.38684542, 0.18967353, 0.41077067, 0.59468007],
       [0.71658609, 0.48689148, 0.30958982, 0.57744137, 0.44170782],
       [0.3596781 , 0.32133193, 0.20820724, 0.45125862, 0.49184291]])

In [123]:
x.mean()

0.4086522725453034

In [129]:
x.max() # np.max()

0.7165860931283399

In [125]:
x.min()

0.18327900063057578

In [126]:
np.var(x) # 분산

0.02220727240878632

In [127]:
np.median(x) # 중앙값

0.41077067302531

In [128]:
x.std()

0.14902104686515366

In [130]:
np.sum(x)

6.129784088179551

In [132]:
np.cumsum(x)

array([0.183279  , 0.57012442, 0.75979795, 1.17056862, 1.76524869,
       2.48183479, 2.96872627, 3.27831609, 3.85575746, 4.29746528,
       4.65714338, 4.97847531, 5.18668255, 5.63794118, 6.12978409])

#### any, all 함수
- any : 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
- all : 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [133]:
z = np.random.randn(10)
z

array([ 0.83850061,  0.28667885,  0.49880758, -0.60366109,  1.30894109,
        1.27590944, -1.28599308, -0.62575643,  0.34171079, -0.13077302])

In [134]:
np.any(z > 0)

True

In [135]:
np.all(z > 0)

False

#### where 함수
- 조건에 따라 선별적으로 값을 선택

In [136]:
# z에서 0보다 크면 그대로 요소를 사용하고, 0보다 작으면 0으로 변경

np.where(z > 0, z, 0)

array([0.83850061, 0.28667885, 0.49880758, 0.        , 1.30894109,
       1.27590944, 0.        , 0.        , 0.34171079, 0.        ])

### axis(축) 를 파라미터로 갖는 함수 활용

In [142]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
np.sum(x, axis=0)

45

In [144]:
array1 = x.reshape(2, 5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [139]:
print(array1.sum())
print(array1.sum(axis=0))
print(array1.sum(axis=1))

55
55


AxisError: axis 1 is out of bounds for array of dimension 1

In [140]:
y = np.arange(36).reshape(3, 4, 3)
y

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [141]:
print(y.sum())
print(y.sum(axis=0))
print(y.sum(axis=1))
print(y.sum(axis=2))

630
[[36 39 42]
 [45 48 51]
 [54 57 60]
 [63 66 69]]
[[ 18  22  26]
 [ 66  70  74]
 [114 118 122]]
[[  3  12  21  30]
 [ 39  48  57  66]
 [ 75  84  93 102]]


#### 브로드캐스팅
- shape이 같은 연산
- 뒷 차원에서부터 비교하여 shape이 같거나, 차원 중 값이 1인 것이 존재하면 해줌

In [145]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)

print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.15973623 0.9616419  0.83761574 0.52016069 0.21827226]
 [0.13491872 0.97907035 0.7070435  0.85997556 0.38717263]
 [0.25083402 0.29943802 0.85689553 0.47298399 0.66327705]]


In [146]:
x + y

array([[ 0.15973623,  1.9616419 ,  2.83761574,  3.52016069,  4.21827226],
       [ 5.13491872,  6.97907035,  7.7070435 ,  8.85997556,  9.38717263],
       [10.25083402, 11.29943802, 12.85689553, 13.47298399, 14.66327705]])

In [147]:
x + 2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [148]:
x * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [154]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)

print(a)
print()
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[100 101 102]


In [150]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [151]:
c = np.arange(1000, 1004)
c

array([1000, 1001, 1002, 1003])

In [152]:
a + c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [155]:
print(a.shape)
print(b.shape)
print(c.shape)

(4, 3)
(3,)
(4,)


In [156]:
d = b.reshape(1, 3)
d

array([[100, 101, 102]])

In [157]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [158]:
d.shape

(1, 3)

### 행렬의 정렬 - sort(), argsort()

In [160]:
org_array1 = np.array([3, 1, 9, 5])
org_array1

array([3, 1, 9, 5])

In [161]:
# 원본 행렬은 변화가 안됨 : np.sort()
sort_array1 = np.sort(org_array1)
print(sort_array1)
print(org_array1)

[1 3 5 9]
[3 1 9 5]


In [162]:
# 원본을 변경
sort_array2 = org_array1.sort()
print(sort_array2)
print(org_array1)

None
[1 3 5 9]


In [9]:
# soflacktns wjdfuf
org_array1 = np.array([3, 1, 9, 5])
org_array1

array([3, 1, 9, 5])

In [11]:
sort_array2 = np.sort(org_array1)[::-1]
sort_array2

array([9, 5, 3, 1])

In [12]:
array2d = np.array([[8, 12], [7, 1]])
array2d

array([[ 8, 12],
       [ 7,  1]])

In [13]:
array2d_sort = np.sort(array2d)
array2d_sort

array([[ 8, 12],
       [ 1,  7]])

In [14]:
array2d_sort = np.sort(array2d, axis = 0) # 가로는 1, 세로는 0
array2d_sort

array([[ 7,  1],
       [ 8, 12]])

- argosrt() : 원본 행렬이 정렬된 후의 인덱스 번호

In [15]:
org_array1

array([3, 1, 9, 5])

In [17]:
sort_indices = np.argsort(org_array1)
sort_indices

array([1, 0, 3, 2], dtype=int64)

In [18]:
sort_indices = np.argsort(org_array1)[::-1]
sort_indices

array([2, 3, 0, 1], dtype=int64)

In [20]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

print(name_array)
print(score_array)

['John' 'Mike' 'Sarah' 'Kate' 'Samuel']
[78 95 84 98 88]


In [22]:
sort_indices_asc = np.argsort(score_array)

print(sort_indices_asc)
print(name_array[sort_indices_asc])

[0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [23]:
sort_indices_desc = np.argsort(score_array)[::-1]
print(name_array[sort_indices_desc])

['Kate' 'Mike' 'Samuel' 'Sarah' 'John']


전치 행렬 : 행과 열 위치를 변경

In [24]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [25]:
transpose_a = np.transpose(a)
transpose_a

array([[1, 3],
       [2, 4]])